apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-store
spec:
  selector:
    matchLabels:
      app: online-store
  template:
    metadata:
      labels:
        app: online-store
    spec:
      containers:
      - name: authentication-ms
        image: guilhermemr/osauthentication:v1
        ports:
        - containerPort: 3000
      - name: server
        image: guilhermemr/osserver:v1
        ports:
        - containerPort: 3001
      - name: gateway
        image: guilhermemr/osgateway:v1
        ports:
          - containerPort: 3002
      - name: catalog-ms
        image: guilhermemr/oscatalog:v1
        ports:
          - containerPort: 3003
      - name: cart
        image: guilhermemr/oscart:v1
        ports:
          - containerPort: 3004
      - name: order
        image: guilhermemr/osorder:v1
        ports:
          - containerPort: 3005
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: data
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: passwords
              key: DB_PASSWORD
        - name: REDIS_HOST 
          valueFrom:
            configMapKeyRef:
              name: data 
              key: REDIS_HOST 

      livenessProbe:
        httpGet:
          path: /sing-in
          port: 3000
        initialDelaySeconds: 10
        periodSeconds: 3